authors:
  cangjingyue:
    name: 苍镜月    # Author name
    description: 相信的心就是你的魔法！ # Author description
    avatar: https://c-ssl.duitang.com/uploads/item/201812/03/20181203164357_grlsq.thumb.1000_0.png