authors:
  Wcowin:
    name: 苍镜月    # Author name
    description: 相信的心就是你的魔法！ # Author description
    # avatar: https://s1.imagehub.cc/images/2024/02/02/79cb7379982d1c7bb0ae7163985609c4.jpeg # Author avatar